access_token = '70db120a-c08e-4c33-8f1d-b29254527278'
device_id = 'd53f91fb-b2ba-469b-8817-a4849dd74783'
license_key = '18Shl23W-980eanR5-74KB93Ec'
private_key = 'yE0Ir9pNZrzF2vj7yQJWYxr3kvcV+MmLNJNRy1m8AXg='
