version: "3.9"
services:
  api:
    build: ./apps/api
    env_file: .env
    ports: ["3000:3000"]
    depends_on: [redis]
    networks: [appnet]

  worker:
    build: ./apps/worker
    env_file: .env
    depends_on: [redis]
    networks: [appnet]

  web:
    build: ./apps/web
    env_file: .env.web
    ports: ["5173:5173"]
    networks: [appnet]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    networks: [appnet]

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: ["80:80","443:443"]
    depends_on: [api, web]
    networks: [appnet]

networks:
  appnet: {}
